/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IFeeSplitterSpokeInterface extends Interface {
  getFunction(nameOrSignature: "splitFees"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "splitFees",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "splitFees", data: BytesLike): Result;
}

export interface IFeeSplitterSpoke extends BaseContract {
  connect(runner?: ContractRunner | null): IFeeSplitterSpoke;
  waitForDeployment(): Promise<this>;

  interface: IFeeSplitterSpokeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  splitFees: TypedContractMethod<
    [feeZ: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        toTreasury: bigint;
        toInsurance: bigint;
        toReferral: bigint;
      }
    ],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "splitFees"
  ): TypedContractMethod<
    [feeZ: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        toTreasury: bigint;
        toInsurance: bigint;
        toReferral: bigint;
      }
    ],
    "nonpayable"
  >;

  filters: {};
}
