/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IFundingModuleInterface extends Interface {
  getFunction(
    nameOrSignature: "getFundingIndex" | "updateFundingIndex"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getFundingIndex",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFundingIndex",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getFundingIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFundingIndex",
    data: BytesLike
  ): Result;
}

export interface IFundingModule extends BaseContract {
  connect(runner?: ContractRunner | null): IFundingModule;
  waitForDeployment(): Promise<this>;

  interface: IFundingModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFundingIndex: TypedContractMethod<[marketId: BytesLike], [bigint], "view">;

  updateFundingIndex: TypedContractMethod<
    [marketId: BytesLike, indexDelta: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getFundingIndex"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateFundingIndex"
  ): TypedContractMethod<
    [marketId: BytesLike, indexDelta: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
