/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IMarginVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accountEquityZUSD"
      | "deposit"
      | "release"
      | "reserve"
      | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "accountEquityZUSD",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike, BigNumberish, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "release",
    values: [AddressLike, AddressLike, BigNumberish, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reserve",
    values: [AddressLike, AddressLike, BigNumberish, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish, boolean, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "accountEquityZUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reserve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export interface IMarginVault extends BaseContract {
  connect(runner?: ContractRunner | null): IMarginVault;
  waitForDeployment(): Promise<this>;

  interface: IMarginVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accountEquityZUSD: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  deposit: TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      isolated: boolean,
      marketId: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  release: TypedContractMethod<
    [
      user: AddressLike,
      asset: AddressLike,
      amount: BigNumberish,
      isolated: boolean,
      marketId: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  reserve: TypedContractMethod<
    [
      user: AddressLike,
      asset: AddressLike,
      amount: BigNumberish,
      isolated: boolean,
      marketId: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      isolated: boolean,
      marketId: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accountEquityZUSD"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      isolated: boolean,
      marketId: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<
    [
      user: AddressLike,
      asset: AddressLike,
      amount: BigNumberish,
      isolated: boolean,
      marketId: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reserve"
  ): TypedContractMethod<
    [
      user: AddressLike,
      asset: AddressLike,
      amount: BigNumberish,
      isolated: boolean,
      marketId: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      isolated: boolean,
      marketId: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
