/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICollateralManager } from "./ICollateralManager";
export type { IFeeSplitterSpoke } from "./IFeeSplitterSpoke";
export type { IFundingModule } from "./IFundingModule";
export type { IMarginVault } from "./IMarginVault";
export type { IOracleRouter } from "./IOracleRouter";
export type { IPerpEngine } from "./IPerpEngine";
export type { IRiskConfig } from "./IRiskConfig";
export type { ITreasurySpoke } from "./ITreasurySpoke";
