/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOracleRouter,
  IOracleRouterInterface,
} from "../../../../src/core/interfaces/IOracleRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getPriceInZUSD",
    outputs: [
      {
        internalType: "uint256",
        name: "priceX1e18",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "isStale",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IOracleRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IOracleRouterInterface {
    return new Interface(_abi) as IOracleRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IOracleRouter {
    return new Contract(address, _abi, runner) as unknown as IOracleRouter;
  }
}
