/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPerpEngine,
  IPerpEngineInterface,
} from "../../../../src/core/interfaces/IPerpEngine";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "computeAccountMMRZ",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "marketId",
        type: "bytes32",
      },
    ],
    name: "getPosition",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "getUnrealizedPnlZ",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "fillId",
            type: "bytes32",
          },
          {
            internalType: "address",
            name: "account",
            type: "address",
          },
          {
            internalType: "bytes32",
            name: "marketId",
            type: "bytes32",
          },
          {
            internalType: "bool",
            name: "isBuy",
            type: "bool",
          },
          {
            internalType: "uint128",
            name: "size",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "priceZ",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "feeZ",
            type: "uint128",
          },
          {
            internalType: "int128",
            name: "fundingZ",
            type: "int128",
          },
          {
            internalType: "uint64",
            name: "ts",
            type: "uint64",
          },
        ],
        internalType: "struct IPerpEngine.Fill",
        name: "f",
        type: "tuple",
      },
    ],
    name: "recordFill",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPerpEngine__factory {
  static readonly abi = _abi;
  static createInterface(): IPerpEngineInterface {
    return new Interface(_abi) as IPerpEngineInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IPerpEngine {
    return new Contract(address, _abi, runner) as unknown as IPerpEngine;
  }
}
