/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITreasurySpoke,
  ITreasurySpokeInterface,
} from "../../../../src/core/interfaces/ITreasurySpoke";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ITreasurySpoke__factory {
  static readonly abi = _abi;
  static createInterface(): ITreasurySpokeInterface {
    return new Interface(_abi) as ITreasurySpokeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITreasurySpoke {
    return new Contract(address, _abi, runner) as unknown as ITreasurySpoke;
  }
}
