/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { Constants, ConstantsInterface } from "../../lib/Constants";

const _abi = [
  {
    inputs: [],
    name: "DEFAULT_ADMIN",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "DEFAULT_MAX_STALE",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ENGINE",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ENGINE_ADMIN",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "INTERNAL_DECIMALS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "KEEPER",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "LTV_NON_STABLE_BPS",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "LTV_STABLE_BPS",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAKER_FEE_BPS_DEFAULT",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PRICE_DECIMALS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PRICE_KEEPER",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "RISK_ADMIN",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "TAKER_FEE_BPS_DEFAULT",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "TREASURER",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523461001a576102e19081610020823930815050f35b600080fdfe60806040818152600436101561001457600080fd5b600091823560e01c90816307dc8c30146102535750806335b6c2451461023c5780634444315d146102265780634785e8d4146101f157806350317846146101db57806359e93967146101a65780637252ec0e14610171578063862a179e1461013c57806398a45448146101255780639cdeba9514610110578063be406e6c146100f4578063ec797b1c146100f9578063f1a640f8146100f45763fb1849ee146100bc57600080fd5b816003193601126100f057602090517f8d9233e8f9e0681d692bebdd2fd8c8863336d587e831d84b9bff9f403d549b5f8152f35b5080fd5b610288565b50816003193601126100f057602090516127108152f35b50816003193601126100f05751908152602090f35b50816003193601126100f0576020905161012c8152f35b50816003193601126100f057602090517f71a9859d7dd21b24504a6f306077ffc2d510b4d4b61128e931fe937441ad18368152f35b50816003193601126100f057602090517f8aa855a911518ecfbe5bc3088c8f3dda7badf130faaf8ace33fdc33828e181678152f35b50816003193601126100f057602090517ff0fcaef9f8ed10d22ffdcbc513b341e7ac8baa5f1d5771a318a3f439fda443f78152f35b50816003193601126100f0576020905160058152f35b50816003193601126100f057602090517fbc7594c22daadcbde6fe7c5e4e2f2d5966e1ecafeeeb82209b62000d005d6c318152f35b50816003193601126100f0576020905160078152f35b50816003193601126100f057602090516113888152f35b8390816003193601126100f057807f151ff8b4d0da3f5c5fabf30466470e82bc2019e5d78c902a7dc3f2aa4c0bdbcc60209252f35b60003660031901126102a6576020604051670de0b6b3a76400008152f35b600080fdfea2646970667358221220a494d587c38797fed492647bb9a5760989a89613179cbccf0657b631ef99a30164736f6c63430008180033";

type ConstantsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ConstantsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Constants__factory extends ContractFactory {
  constructor(...args: ConstantsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Constants & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Constants__factory {
    return super.connect(runner) as Constants__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ConstantsInterface {
    return new Interface(_abi) as ConstantsInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Constants {
    return new Contract(address, _abi, runner) as unknown as Constants;
  }
}
